blueprints/qa.py
# encoding: utf-8
"""
@author: xiejun
@contact: 1079658140@qq.com
@software: PyCharm
@file: qa.py
@time: 2022/4/24 16:27
"""

from flask import Blueprint, render_template, request, g, redirect, url_for, flash
from sqlalchemy import or_

from blueprints.forms import QusetionForm, AnswerForm
from decorators import login_required
from exts import db
from models import QuestionModel, AnswerModel

bp = Blueprint('qa', __name__, url_prefix='/')


@bp.route('/', methods=['GET', 'POST'])
def index():
    questions = QuestionModel.query.order_by(db.text("-create_time")).all()
    return render_template('index.html', questions=questions)


@bp.route('/question/public', methods=['GET', 'POST'])
@login_required  # 装饰器，需要登录才能访问
def public_question():
    # 判断是否登录，如果没有登录，跳转到登录页面
    if request.method == 'GET':
        return render_template('public_question.html')
    else:
        form = QusetionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect('/')
        else:
            flash('标题或格式错误')
            return redirect(url_for("qa.public_question"))


@bp.route("/question/<int:question_id>")
def question_detail(question_id):
    question = QuestionModel.query.get(question_id)
    return render_template('detail.html', question=question)


@bp.route("/answer/<int:question_id>", methods=['POST'])
@login_required
def answer(question_id):
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        # question_id = form.question_id.data
        answer_model = AnswerModel(content=content, author=g.user, question_id=question_id)
        db.session.add(answer_model)
        db.session.commit()
        return redirect(url_for('qa.question_detail', question_id=question_id))
    else:
        flash('回答格式错误')
        return redirect(url_for('qa.question_detail', question_id=question_id))


@bp.route("search")
def search():
    q = request.args.get('q')
    questions = QuestionModel.query.filter(or_(QuestionModel.title.contains(q),
                                               QuestionModel.content.contains(q))).order_by(db.text("-create_time"))
    return render_template('index.html', questions=questions)

blueprints/user.py
# encoding: utf-8
"""
@author: xiejun
@contact: 1079658140@qq.com
@software: PyCharm
@file: user.py
@time: 2022/4/24 16:27
"""
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, \
    url_for, jsonify, session,flash
from werkzeug.security import generate_password_hash, check_password_hash
from exts import mail, db
from flask_mail import Message
from models import EmailCaptchModel, Usermodel
import string
import random
from .forms import RegisterForm, LoginForm

bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = Usermodel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password, password):
                session['user_id'] = user.id
                return redirect('/')
            else:
                flash("邮箱或密码错误")
                return redirect(url_for('user.login'))
        else:
            flash("邮箱或密码格式错误")
            return redirect(url_for('user.login'))  # 返回登录页面


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            # md5加密
            hash_password = generate_password_hash(password)
            user = Usermodel(email=email, username=username, password=hash_password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('user.login'))
        else:
            return render_template('register.html', form=form)


@bp.route("/captcha", methods=['POST'])
def get_captcha():
    """
    获取验证码
    :return:
    """
    #  使用get post方法
    email = request.form.get('email')
    # 随机生成一个字符串
    s = string.ascii_letters + string.digits
    captcha = "".join(random.sample(s, 4))
    if email:
        message = Message("测试邮件", recipients=[email], body=f"【谢军问答】，您的验证码是：{captcha}")
        mail.send(message)
        captcha_model = EmailCaptchModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchModel(email=email, captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
        print("captcha:", captcha)
        return jsonify({"code": 200, "msg": "获取成功"})
    else:
        return jsonify({"code": 400, "msg": "请先传递邮箱！"})

@bp.route('/logout')
def logout():
    # 清楚session所有数据
    session.clear()
    return redirect(url_for('user.login'))  #

templates/base.html
<body>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap.4.6.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
         <a class="navbar-brand" href="/">谢军问答</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('qa.public_question') }}">发布问答</a>
      </li>
        <li class="nav-item ml-2">
        <form class="form-inline  my-3 my-lg-0" method="get" action="{{ url_for('qa.search') }}">
          <input class="form-control mr-sm-2" type="search" placeholder="" aria-label="Search" name="q">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit" >搜索</button>
        </form>
        </li>
    </ul>
      <ul class="navbar-nav">
          {% if user %}
            <li class="nav-item">
            <a class="nav-link" >{{user.username}} </a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
            </li>
          {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">登录 </a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
            </li>
        {% endif %}
    </ul>
  </div>
      </div>
</nav>
<div class="container">{% block body %}{% endblock %}</div>
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}{{ question.title }}{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px">
    <div class="col"></div>
    <div class="col-8" style="background-color: #ffffff; padding: 20px">
      <h3 class="page-title">{{ question.title }}</h3>
      <p class="question-info">
        <span>作者:{{ question.author.username }}</span>
        <span>时间：{{ question.create_time }}</span>
      </p>
      <hr>
      <p class="question-content">{{ question.content }}</p>
      <hr>

      <h4 class="comment-group-title">评论 ({{ question.answers|length }})</h4>
      <form action="{{ url_for('qa.answer',question_id=question.id) }}" method="post">
        {#        <input type="hidden" class="question_id" value="{{ question_id }}">#}
        <div class="from-group">
          <input type="text" placeholder="请输入评论" name="content" class="form-control">
        </div>
        <div class="from-group  " style="text-align: right;margin-top: 10px">
          <button class="btn btn-primary">评论</button>
        </div>
      </form>
      <ul class="comment-group">
        {% for answer in question.answers %}
          <li>
            <div class="user-info">
              <img src="{{ url_for('static',filename='images/1.jpg') }}" alt="" class="avatar">
              <span class="username">{{answer.author.username}}</span>
              <span class="create_time">{{answer.create_time}}</span>
            </div>
            <p class="comment-content">{{answer.content}}</p>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col"></div>
  </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}谢军问答-首页{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px">
  <div class="col"></div>
  <div class="col-8">
    {% for question in questions %}
      <ul class="question-ul">
      <li>
        <div class="side-question">
          <img src="{{url_for('static',filename='images/2.png')}}" alt="" class="side-question-avatar">
        </div>
        <div class="question-main">
          <div class="question-title"><a href="{{url_for('qa.question_detail',question_id=question.id)}}">{{question.title}}</a></div>
          <div class="question-content">{{question.content}}</div>
          <div class="question-detail">
            <span class="question-author">{{question.author.username}}</span>
            <span class="question-time">{{question.create_time}}</span>
          </div>
        </div>
      </li>
    </ul>
    {% endfor %}

  </div>
  <div class="col"></div>
  </div>
{% endblock %}

templates/indexbak.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>谢军问答-首页</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap.4.6.min.css') }}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
         <a class="navbar-brand" href="#">谢军问答</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">首页 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">发布问答</a>
      </li>
        <li class="nav-item ml-2">
                <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">查询</button>
                </form>
        </li>
    </ul>
      <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">登录 </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">注册</a>
      </li>
    </ul>
  </div>
      </div>
</nav>
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% block title %}谢军问答-登录{% endblock %}
{% block head %}

{% endblock %}

{% block body %}
  <div class="row mt-4">
    <div class="col-sm"></div>
    <div class="col-sm">
      <form action="{{ url_for('user.login') }}" method="post">
        <div class="form-group">
          <label for="exampleInputEmail1">邮箱</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
          {#      <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用处</small>#}
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">密码</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>


        {% for message in get_flashed_messages() %}
          <div class="form-group">
            <p class="text-danger">{{ message }}</p>
          </div>
        {% endfor %}



        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">登录</button>
        </div>
      </form>
    </div>
    <div class="col-sm"></div>
  </div>
{% endblock %}

templates/public_question.html
{% extends "base.html" %}

{% block title %}发布问答{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8">
      <h3 style="text-align: center">发布问题</h3>
      <form action="{{ url_for("qa.public_question") }}" method="post">
        <div class="form-group">
          <input type="text" name="title" class="form-control" placeholder="请输入标题">
        </div>
        <div class="form-group">
          <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
        </div>

        {% for message in get_flashed_messages() %}
          <div class="form-group">
            <p class="text-danger">{{ message }}</p>
          </div>
        {% endfor %}


        <div class="form-group" style="text-align: right">
          <button class="btn btn-primary" type="submit">发布</button>
        </div>
      </form>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block title %}谢军问答-注册{% endblock %}
{% block head %}
  <script src="{{ url_for('static',filename='jquery/jquery.3.6.min.js') }}"></script>
  <script src="{{ url_for('static',filename='js/register.js') }}"></script>
{% endblock %}

{% block body %}
  <div class="row mt-4">
    <div class="col-sm"></div>
    <div class="col-sm">
      <form method="post" action="{{ url_for('user.register') }}">
    <div class="form-group">
      <label for="exampleInputEmail1">邮箱</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
      <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用处</small>
    </div>

    <div class="form-group">
      <label for="exampleInputEmail1">验证码</label>
      <div class="input-group is-invalid">
        <input type="text" class="form-control" name="captcha">
          <div class="input-group-append">
          <button class="btn btn-outline-primary" type="button" id="captcha-btn">获取验证码</button>
          </div>
      </div>
    </div>

    <div class="form-group">
      <label for="exampleInputEmail1">用户名</label>
      <input type="username" class="form-control"  name="username">
    </div>


    <div class="form-group">
      <label for="exampleInputPassword1">密码</label>
      <input type="password" class="form-control" id="exampleInputPassword1" name="password">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">确认密码</label>
      <input type="password" class="form-control" name="password_confirm">
    </div>
{#    <div class="form-group form-check">#}
{#      <input type="checkbox" class="form-check-input" id="exampleCheck1">#}
{#      <label class="form-check-label" for="exampleCheck1">Check me out</label>#}
{#    </div>#}
    <button type="submit" class="btn btn-primary btn-block">注册</button>
  </form>
    </div>
    <div class="col-sm"></div>
  </div>
{% endblock %}